import { requireAuth, verifySameOrigin } from '@/lib/auth'; import { MAX_ATTACHMENTS } from '@/lib/constants'; import { ensureDatabase, getD1, getFiles } from '@/lib/database'; import { validateFile } from '@/lib/files'; import { jsonError } from '@/lib/http';
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  const unauthorized = await requireAuth(request); if (unauthorized) return unauthorized; if (!verifySameOrigin(request)) return jsonError('请求来源不可信', 403); await ensureDatabase(); const { id: transactionId } = await context.params;
  const transaction = await getD1().prepare('SELECT id FROM transactions WHERE id = ? AND deleted_at IS NULL').bind(transactionId).first(); if (!transaction) return jsonError('账单不存在', 404);
  const count = await getD1().prepare('SELECT COUNT(*) AS count FROM attachments WHERE transaction_id = ? AND deleted_at IS NULL').bind(transactionId).first<{ count: number }>(); if ((count?.count || 0) >= MAX_ATTACHMENTS) return jsonError('每笔账单最多10个附件');
  const form = await request.formData(); const file = form.get('file'); const preview = form.get('preview'); if (!(file instanceof File)) return jsonError('请选择文件'); const validationError = await validateFile(file); if (validationError) return jsonError(validationError);
  if (preview instanceof File && (preview.type !== 'image/webp' || preview.size > 2 * 1024 * 1024)) return jsonError('HEIC预览文件不正确');
  const attachmentId = crypto.randomUUID(); const extension = file.name.split('.').pop()?.toLowerCase() || 'bin'; const objectKey = `transactions/${transactionId}/${attachmentId}.${extension}`; const previewKey = preview instanceof File ? `transactions/${transactionId}/${attachmentId}-preview.webp` : null;
  await getFiles().put(objectKey, file.stream(), { httpMetadata: { contentType: file.type } }); if (preview instanceof File && previewKey) await getFiles().put(previewKey, preview.stream(), { httpMetadata: { contentType: 'image/webp' } });
  const now = new Date().toISOString(); await getD1().prepare('INSERT INTO attachments (id, transaction_id, object_key, preview_object_key, original_name, content_type, size_bytes, created_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL)').bind(attachmentId, transactionId, objectKey, previewKey, file.name.slice(0, 180), file.type, file.size, now).run(); return Response.json({ id: attachmentId }, { status: 201 });
}
