'use client';
/* eslint-disable @next/next/no-html-link-for-pages -- Full-page navigation avoids Vinext RSC prefetch failures in the self-hosted Worker runtime. */
import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Image as ImageIcon, LoaderCircle, WalletCards } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AppShell, InlineLink } from '@/components/app-shell'; import { Card } from '@/components/ui/card'; import { api, dateTime, money, type Transaction } from '@/lib/types';
type DashboardData = { month: string; summary: { expense: number; income: number; balance: number; previousExpense: number; expenseChange: number | null }; categories: Array<{ id: string; name: string; color: string; icon: string; amountCents: number }>; trend: Array<{ month: string; expense: number; income: number }>; recent: Transaction[] };
function Loading() { return <div className="grid min-h-[360px] place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/><span className="sr-only">正在加载</span></div>; }
export function DashboardView() {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState('');
  useEffect(() => { api<DashboardData>('/api/dashboard').then(setData).catch((reason) => setError(reason.message)); }, []);
  return <AppShell title="晚上好，看看这个月吧">{!data && !error ? <Loading/> : error ? <Card className="p-6 text-sm text-[var(--danger)]">{error}</Card> : data ? <DashboardContent data={data}/> : null}</AppShell>;
}
function DashboardContent({ data }: { data: DashboardData }) {
  const summary = [
    { label: '本月支出', value: data.summary.expense, note: data.summary.expenseChange === null ? '还没有上月数据' : `较上月 ${data.summary.expenseChange <= 0 ? '下降' : '增加'} ${Math.abs(data.summary.expenseChange * 100).toFixed(1)}%`, icon: ArrowDownRight, tone: 'text-[var(--expense)] bg-[var(--danger-soft)]' },
    { label: '本月收入', value: data.summary.income, note: data.summary.income ? '本月收入已记录' : '记下第一笔收入', icon: ArrowUpRight, tone: 'text-[var(--income)] bg-[var(--brand-soft)]' },
    { label: '本月结余', value: data.summary.balance, note: data.summary.income ? `结余率 ${((data.summary.balance / data.summary.income) * 100).toFixed(1)}%` : '收入减去支出', icon: WalletCards, tone: 'text-[#a1712f] bg-[#f6eddd]' },
  ];
  const trend = data.trend.map((row) => ({ ...row, label: `${Number(row.month.slice(5))}月`, expenseYuan: row.expense / 100, incomeYuan: row.income / 100 }));
  const pie = data.categories.slice(0, 5).map((item) => ({ ...item, value: item.amountCents }));
  return <>
    <section aria-label="本月概览" className="grid gap-3 sm:grid-cols-3">{summary.map(({ label, value, note, icon: Icon, tone }) => <Card key={label} className="p-5"><div className="flex items-center justify-between"><p className="text-sm font-medium text-[var(--muted)]">{label}</p><span className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon size={18}/></span></div><p className="mt-4 font-mono text-[25px] font-semibold tracking-[-0.04em] sm:text-[27px]">{money(value)}</p><p className="mt-2 text-xs text-[var(--muted)]">{note}</p></Card>)}</section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.75fr)]">
      <Card className="p-5 sm:p-6"><div><h2 className="text-base font-semibold">收支趋势</h2><p className="mt-1 text-sm text-[var(--muted)]">最近6个月，单位：元</p></div>{trend.some((row) => row.expense || row.income) ? <div className="mt-6 h-[250px]" aria-label="近六个月收入与支出柱状图"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ left: -22, right: 4 }}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }}/><Tooltip cursor={{ fill: 'var(--hover)' }} formatter={(value) => money(Number(value) * 100)} contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 12 }}/><Bar dataKey="expenseYuan" name="支出" fill="var(--brand)" radius={[5, 5, 0, 0]}/><Bar dataKey="incomeYuan" name="收入" fill="#d4a653" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div> : <EmptyChart/>}<div className="mt-3 flex items-center gap-5 text-xs text-[var(--muted)]"><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[var(--brand)]"/>支出</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[#d4a653]"/>收入</span></div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold">支出分类</h2><p className="mt-1 text-sm text-[var(--muted)]">本月共 {money(data.summary.expense)}</p></div><InlineLink href="/transactions?type=expense">详情</InlineLink></div>{pie.length ? <><div className="mx-auto mt-4 h-[160px] w-full max-w-[230px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={46} outerRadius={68} paddingAngle={2}>{pie.map((entry) => <Cell key={entry.id} fill={entry.color}/>)}</Pie><Tooltip formatter={(value) => money(Number(value))} contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 12 }}/></PieChart></ResponsiveContainer></div><dl className="space-y-2.5">{pie.map((item) => <div key={item.id} className="flex items-center gap-2 text-sm"><i className="size-2.5 rounded-full" style={{ backgroundColor: item.color }}/><dt className="text-[var(--muted)]">{item.name}</dt><dd className="ml-auto font-mono font-semibold">{money(item.amountCents)}</dd></div>)}</dl></> : <div className="grid h-[240px] place-items-center text-center"><div><p className="text-sm font-semibold">还没有支出数据</p><p className="mt-1 text-xs text-[var(--muted)]">记一笔后，分类占比会显示在这里。</p></div></div>}</Card>
    </div>
    <Card className="mt-4"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-5 sm:px-6"><div><h2 className="text-base font-semibold">最近账单</h2><p className="mt-1 text-sm text-[var(--muted)]">及时记录，心里有数</p></div><InlineLink href="/transactions">查看全部</InlineLink></div>{data.recent.length ? <div className="divide-y divide-[var(--line)] px-2 sm:px-3">{data.recent.map((transaction) => <a key={transaction.id} href={`/transactions/${transaction.id}`} className="flex min-h-[76px] items-center gap-3 rounded-xl px-3 py-3 hover:bg-[var(--hover)] sm:px-4"><span className="grid size-11 shrink-0 place-items-center rounded-[14px] text-sm font-semibold" style={{ color: transaction.categoryColor || 'var(--muted)', backgroundColor: `${transaction.categoryColor || '#77837e'}18` }}>{transaction.categoryName?.slice(0, 1) || '账'}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{transaction.title}</span><span className="mt-1 flex items-center gap-1 text-xs text-[var(--muted)]">{transaction.categoryName || '未分类'} · {dateTime(transaction.occurredAt)} {transaction.attachmentCount ? <><ImageIcon size={13}/>{transaction.attachmentCount}</> : null}</span></span><span className={`ml-auto shrink-0 font-mono text-sm font-semibold ${transaction.type === 'income' ? 'text-[var(--income)]' : ''}`}>{money(transaction.amountCents, transaction.type)}</span></a>)}</div> : <div className="px-6 py-14 text-center"><ReceiptEmpty/><p className="mt-3 text-sm font-semibold">账本还是空的</p><p className="mt-1 text-sm text-[var(--muted)]">从第一笔真实记录开始。</p><a href="/transactions/new" className="mt-4 inline-flex min-h-10 items-center text-sm font-semibold text-[var(--brand)]">现在记一笔</a></div>}</Card>
  </>;
}
function EmptyChart() { return <div className="grid h-[250px] place-items-center text-center"><div><ChartNoData/><p className="mt-2 text-sm font-semibold">趋势将在这里出现</p><p className="text-xs text-[var(--muted)]">至少记录一笔账单即可开始分析。</p></div></div>; }
function ChartNoData() { return <span className="mx-auto flex h-12 w-16 items-end justify-center gap-1.5"><i className="h-5 w-2.5 rounded-t bg-[var(--line)]"/><i className="h-9 w-2.5 rounded-t bg-[var(--line)]"/><i className="h-7 w-2.5 rounded-t bg-[var(--line)]"/></span>; }
function ReceiptEmpty() { return <span className="mx-auto block size-12 rounded-2xl border border-dashed border-[var(--line-strong)] bg-[var(--page)]"/>; }
