'use client';
/* eslint-disable @next/next/no-img-element -- authenticated R2 images must bypass the public image optimizer */
/* eslint-disable @next/next/no-html-link-for-pages -- Full-page navigation avoids Vinext RSC prefetch failures in the self-hosted Worker runtime. */
import { useEffect, useState } from 'react'; import * as Dialog from '@radix-ui/react-dialog';
import { ArrowLeft, Download, Edit3, File, FileImage, FileText, LoaderCircle, Paperclip, Trash2, X } from 'lucide-react';
import { AppShell } from '@/components/app-shell'; import { Button, buttonClass } from '@/components/ui/button'; import { Card } from '@/components/ui/card'; import { api, dateTime, fileSize, money, type Attachment, type Transaction } from '@/lib/types';
export function TransactionDetail({ transactionId }: { transactionId: string }) {
  const [detail, setDetail] = useState<{ transaction: Transaction; attachments: Attachment[] } | null>(null); const [error, setError] = useState(''); const [preview, setPreview] = useState<Attachment | null>(null);
  const load = () => api<{ transaction: Transaction; attachments: Attachment[] }>(`/api/transactions/${transactionId}`).then(setDetail).catch((reason) => setError(reason.message)); useEffect(() => { api<{ transaction: Transaction; attachments: Attachment[] }>(`/api/transactions/${transactionId}`).then(setDetail).catch((reason) => setError(reason.message)); }, [transactionId]);
  const removeBill = async () => { if (!window.confirm('账单及其附件将进入回收站，可在30天内恢复。继续吗？')) return; try { await api(`/api/transactions/${transactionId}`, { method: 'DELETE' }); window.location.replace('/transactions'); } catch (reason) { setError(reason instanceof Error ? reason.message : '删除失败'); } };
  const removeAttachment = async (id: string) => { if (!window.confirm('附件将进入回收站，可在30天内恢复。继续吗？')) return; try { await api(`/api/attachments/${id}`, { method: 'DELETE' }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '附件删除失败'); } };
  return <AppShell title="账单详情" eyebrow="核对信息、查看票据或继续编辑" actions={<div className="flex gap-2"><a href="/transactions" className={buttonClass({ variant: 'secondary' })}><ArrowLeft size={17}/><span className="hidden sm:inline">返回</span></a><a href={`/transactions/${transactionId}/edit`} className={buttonClass()}><Edit3 size={17}/>编辑</a></div>}>
    {!detail && !error ? <div className="grid min-h-[360px] place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div> : error ? <Card className="p-5 text-sm text-[var(--danger)]">{error}</Card> : detail ? <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.7fr)]"><Card className="p-6 sm:p-8"><div className="flex items-start justify-between gap-5"><div><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${detail.transaction.type === 'expense' ? 'bg-[var(--danger-soft)] text-[var(--expense)]' : 'bg-[var(--brand-soft)] text-[var(--income)]'}`}>{detail.transaction.type === 'expense' ? '支出' : '收入'}</span><h2 className="mt-4 text-2xl font-bold tracking-tight">{detail.transaction.title}</h2><p className={`mt-3 font-mono text-[34px] font-semibold tracking-[-0.05em] ${detail.transaction.type === 'income' ? 'text-[var(--income)]' : ''}`}>{money(detail.transaction.amountCents, detail.transaction.type)}</p></div><span className="grid size-14 shrink-0 place-items-center rounded-2xl text-lg font-bold" style={{ color: detail.transaction.categoryColor || 'var(--muted)', backgroundColor: `${detail.transaction.categoryColor || '#77837e'}18` }}>{detail.transaction.categoryName?.slice(0, 1) || '账'}</span></div><dl className="mt-8 grid gap-0 rounded-2xl border border-[var(--line)] sm:grid-cols-2">{[['分类', detail.transaction.categoryName || '未分类'], ['支付方式', detail.transaction.paymentMethod || '未记录'], ['发生时间', dateTime(detail.transaction.occurredAt)], ['币种', '人民币 CNY']].map(([term, value]) => <div key={term} className="border-b border-[var(--line)] p-4 last:border-b-0 sm:[&:nth-child(odd)]:border-r sm:[&:nth-last-child(-n+2)]:border-b-0"><dt className="text-xs text-[var(--muted)]">{term}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl>{detail.transaction.note ? <div className="mt-5 rounded-2xl bg-[var(--page)] p-4"><p className="text-xs font-semibold text-[var(--muted)]">备注</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{detail.transaction.note}</p></div> : null}<div className="mt-8 border-t border-[var(--line)] pt-5"><Button variant="danger" onClick={removeBill}><Trash2 size={17}/>移入回收站</Button></div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">附件</h2><p className="mt-1 text-xs text-[var(--muted)]">{detail.attachments.filter((item) => !item.deletedAt).length} 个文件</p></div><Paperclip size={20} className="text-[var(--brand)]"/></div><div className="mt-5 space-y-3">{detail.attachments.filter((item) => !item.deletedAt).map((item) => <AttachmentCard key={item.id} item={item} onPreview={() => setPreview(item)} onDelete={() => removeAttachment(item.id)}/>)}{!detail.attachments.some((item) => !item.deletedAt) ? <div className="rounded-2xl border border-dashed border-[var(--line-strong)] px-4 py-12 text-center"><Paperclip className="mx-auto text-[var(--muted)]"/><p className="mt-3 text-sm font-semibold">还没有附件</p><a href={`/transactions/${transactionId}/edit`} className="mt-2 inline-flex text-sm font-semibold text-[var(--brand)]">去添加票据</a></div> : null}</div></Card></div> : null}
    <PreviewDialog item={preview} onOpenChange={(open) => !open && setPreview(null)}/>
  </AppShell>;
}
function AttachmentCard({ item, onPreview, onDelete }: { item: Attachment; onPreview: () => void; onDelete: () => void }) { const previewable = item.contentType.startsWith('image/') || item.contentType === 'application/pdf'; const Icon = item.contentType.startsWith('image/') ? FileImage : item.contentType === 'application/pdf' ? FileText : File; return <div className="group flex items-center gap-3 rounded-2xl border border-[var(--line)] p-3"><button type="button" onClick={previewable ? onPreview : undefined} disabled={!previewable} className="grid size-12 shrink-0 place-items-center rounded-xl bg-[var(--page)] text-[var(--brand)] disabled:text-[var(--muted)]" aria-label={previewable ? `预览${item.originalName}` : undefined}><Icon size={20}/></button><button type="button" onClick={previewable ? onPreview : undefined} disabled={!previewable} className="min-w-0 flex-1 text-left"><span className="block truncate text-sm font-semibold">{item.originalName}</span><span className="mt-1 block text-xs text-[var(--muted)]">{fileSize(item.sizeBytes)}{previewable ? ' · 点击预览' : ' · 可下载'}</span></button><a href={`/api/attachments/${item.id}?download=1`} className="grid size-10 place-items-center rounded-xl text-[var(--muted)] hover:bg-[var(--hover)] hover:text-[var(--ink)]" aria-label={`下载${item.originalName}`}><Download size={17}/></a><Button variant="ghost" size="icon" aria-label={`删除${item.originalName}`} onClick={onDelete}><Trash2 size={17}/></Button></div>; }
function PreviewDialog({ item, onOpenChange }: { item: Attachment | null; onOpenChange: (open: boolean) => void }) { if (!item) return null; const source = `/api/attachments/${item.id}${item.previewObjectKey ? '?preview=1' : ''}`; return <Dialog.Root open onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm"/><Dialog.Content aria-describedby={undefined} className="fixed left-1/2 top-1/2 z-50 flex h-[min(86dvh,900px)] w-[min(92vw,1100px)] -translate-x-1/2 -translate-y-1/2 flex-col overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-2xl"><div className="flex items-center gap-3 border-b border-[var(--line)] px-4 py-3"><Dialog.Title className="min-w-0 flex-1 truncate text-sm font-semibold">{item.originalName}</Dialog.Title><a href={`/api/attachments/${item.id}?download=1`} className={buttonClass({ variant: 'secondary', size: 'sm' })}><Download size={16}/>下载</a><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="关闭预览"><X size={18}/></Button></Dialog.Close></div><div className="grid min-h-0 flex-1 place-items-center bg-[var(--page)] p-3">{item.contentType === 'application/pdf' ? <iframe src={`/api/attachments/${item.id}`} title={item.originalName} className="h-full w-full rounded-xl bg-white"/> : <img src={source} alt={`附件预览：${item.originalName}`} className="max-h-full max-w-full rounded-xl object-contain"/>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>; }
