'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Download, FileArchive, Image as ImageIcon, Search, SlidersHorizontal, Trash2 } from 'lucide-react';
import { AppShell } from '@/components/app-shell'; import { Button, buttonClass } from '@/components/ui/button'; import { Card } from '@/components/ui/card'; import { inputClass } from '@/components/ui/fields'; import { api, dateTime, money, type Category, type Transaction } from '@/lib/types'; import { PAYMENT_METHODS } from '@/lib/constants'; import { cn } from '@/lib/cn';
function currentMonth() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; }
export function TransactionsView() {
  const [rows, setRows] = useState<Transaction[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ month: currentMonth(), q: '', type: '', category: '', payment: '' });
  const query = useMemo(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key === 'category' ? 'category' : key, value); }); return params.toString(); }, [filters]);
  const load = () => { setLoading(true); setError(''); Promise.all([api<{ transactions: Transaction[] }>(`/api/transactions?${query}`), api<{ categories: Category[] }>('/api/categories')]).then(([transactions, categoryData]) => { setRows(transactions.transactions); setCategories(categoryData.categories); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); };
  useEffect(() => {
    let active = true;
    Promise.all([api<{ transactions: Transaction[] }>(`/api/transactions?${query}`), api<{ categories: Category[] }>('/api/categories')])
      .then(([transactions, categoryData]) => { if (active) { setRows(transactions.transactions); setCategories(categoryData.categories); } })
      .catch((reason) => { if (active) setError(reason.message); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [query]);
  const remove = async (id: string) => { if (!window.confirm('这笔账单会进入回收站，可在30天内恢复。继续吗？')) return; try { await api(`/api/transactions/${id}`, { method: 'DELETE' }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '删除失败'); } };
  const totalExpense = rows.filter((row) => row.type === 'expense').reduce((sum, row) => sum + row.amountCents, 0); const totalIncome = rows.filter((row) => row.type === 'income').reduce((sum, row) => sum + row.amountCents, 0);
  return <AppShell title="账单" eyebrow="查找、筛选和导出每一笔记录" actions={<Link href="/transactions/new" className={buttonClass()}>记一笔</Link>}>
    <Card className="p-4 sm:p-5"><div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_150px_150px_150px_150px]"><label className="relative"><span className="sr-only">搜索账单</span><Search className="absolute left-3.5 top-3.5 text-[var(--muted)]" size={18}/><input className={`${inputClass} pl-10`} value={filters.q} onChange={(event) => setFilters({ ...filters, q: event.target.value })} placeholder="搜索标题或备注"/></label><input aria-label="月份" className={inputClass} type="month" value={filters.month} onChange={(event) => setFilters({ ...filters, month: event.target.value })}/><select aria-label="收支类型" className={inputClass} value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value })}><option value="">全部类型</option><option value="expense">支出</option><option value="income">收入</option></select><select aria-label="分类" className={inputClass} value={filters.category} onChange={(event) => setFilters({ ...filters, category: event.target.value })}><option value="">全部分类</option>{categories.filter((item) => !item.isHidden).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="支付方式" className={inputClass} value={filters.payment} onChange={(event) => setFilters({ ...filters, payment: event.target.value })}><option value="">全部方式</option>{PAYMENT_METHODS.map((item) => <option key={item}>{item}</option>)}</select></div></Card>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-xs text-[var(--muted)]">筛选结果</p><p className="mt-1 font-mono text-xl font-semibold">{rows.length} 笔</p></Card><Card className="p-4"><p className="text-xs text-[var(--muted)]">收入合计</p><p className="mt-1 font-mono text-xl font-semibold text-[var(--income)]">{money(totalIncome)}</p></Card><Card className="p-4"><p className="text-xs text-[var(--muted)]">支出合计</p><p className="mt-1 font-mono text-xl font-semibold">{money(totalExpense)}</p></Card></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm text-[var(--muted)]"><SlidersHorizontal size={17}/>当前筛选会同步应用到导出文件</div><div className="flex gap-2"><a className={buttonClass({ variant: 'secondary', size: 'sm' })} href={`/api/export/csv?${query}`}><Download size={16}/>CSV</a><a className={buttonClass({ variant: 'secondary', size: 'sm' })} href={`/api/export/archive?${query}`}><FileArchive size={16}/>附件包</a></div></div>
    <Card className="mt-4 overflow-hidden">{error ? <div role="alert" className="border-b border-[var(--line)] bg-[var(--danger-soft)] px-5 py-3 text-sm text-[var(--danger)]">{error}</div> : null}{loading ? <div className="px-6 py-16 text-center text-sm text-[var(--muted)]">正在整理账单…</div> : rows.length ? <div className="divide-y divide-[var(--line)]">{rows.map((row) => <div key={row.id} className="group flex items-center gap-3 px-4 py-4 hover:bg-[var(--hover)] sm:px-6"><a href={`/transactions/${row.id}`} className="contents"><span className="grid size-11 shrink-0 place-items-center rounded-[14px] text-sm font-semibold" style={{ color: row.categoryColor || 'var(--muted)', backgroundColor: `${row.categoryColor || '#77837e'}18` }}>{row.categoryName?.slice(0, 1) || '账'}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{row.title}</span><span className="mt-1 flex flex-wrap items-center gap-1 text-xs text-[var(--muted)]">{row.categoryName || '未分类'} · {row.paymentMethod} · {dateTime(row.occurredAt)}{row.attachmentCount ? <><ImageIcon size={13}/>{row.attachmentCount}</> : null}</span></span><span className={cn('shrink-0 font-mono text-sm font-semibold', row.type === 'income' && 'text-[var(--income)]')}>{money(row.amountCents, row.type)}</span></a><Button variant="ghost" size="icon" aria-label={`删除${row.title}`} onClick={() => remove(row.id)} className="text-[var(--muted)] opacity-100 sm:opacity-0 sm:group-hover:opacity-100 sm:focus:opacity-100"><Trash2 size={17}/></Button></div>)}</div> : <div className="px-6 py-16 text-center"><p className="text-sm font-semibold">没有符合条件的账单</p><p className="mt-1 text-sm text-[var(--muted)]">调整筛选条件，或者记录一笔新的收支。</p></div>}</Card>
  </AppShell>;
}
