import { ensureDatabase, getD1 } from '@/lib/database';
const COOKIE_NAME = 'lightledger_session'; const SESSION_MS = 30 * 86400000;
function bytesToBase64(bytes: Uint8Array) { let binary = ''; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary); }
function fromBase64(value: string) { const binary = atob(value); return Uint8Array.from(binary, (char) => char.charCodeAt(0)); }
function base64Url(bytes: Uint8Array) { return bytesToBase64(bytes).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); }
async function passwordHash(password: string, salt: string, iterations: number) { const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt: fromBase64(salt), iterations }, material, 256); return bytesToBase64(new Uint8Array(bits)); }
async function hmac(value: string, secret: string) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); return base64Url(new Uint8Array(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value)))); }
function constantTimeEqual(a: string, b: string) { if (a.length !== b.length) return false; let mismatch = 0; for (let i = 0; i < a.length; i += 1) mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i); return mismatch === 0; }
async function authConfig() { await ensureDatabase(); return getD1().prepare('SELECT password_salt, password_hash, password_iterations, session_secret, session_version FROM auth_config WHERE id = 1').first<{ password_salt: string; password_hash: string; password_iterations: number; session_secret: string; session_version: number }>(); }
export async function verifyPassword(password: string) { const config = await authConfig(); return !!config && constantTimeEqual(await passwordHash(password, config.password_salt, config.password_iterations), config.password_hash); }
export async function createSessionCookie() { const config = await authConfig(); if (!config) throw new Error('认证尚未初始化'); const expires = Date.now() + SESSION_MS; const payload = `${config.session_version}.${expires}.${crypto.randomUUID()}`; const signature = await hmac(payload, config.session_secret); return `${COOKIE_NAME}=${payload}.${signature}; Path=/; Max-Age=${SESSION_MS / 1000}; HttpOnly; Secure; SameSite=Lax`; }
export function clearSessionCookie() { return `${COOKIE_NAME}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`; }
export async function isAuthenticated(request: Request) { const cookie = request.headers.get('cookie')?.split(';').map((item) => item.trim()).find((item) => item.startsWith(`${COOKIE_NAME}=`)); if (!cookie) return false; const parts = cookie.slice(COOKIE_NAME.length + 1).split('.'); if (parts.length !== 4) return false; const [version, expires, nonce, signature] = parts; if (!nonce || !signature || Number(expires) <= Date.now()) return false; const config = await authConfig(); if (!config || Number(version) !== config.session_version) return false; return constantTimeEqual(await hmac(`${version}.${expires}.${nonce}`, config.session_secret), signature); }
export async function requireAuth(request: Request) { return await isAuthenticated(request) ? null : Response.json({ error: '请先登录' }, { status: 401 }); }
export function verifySameOrigin(request: Request) { const origin = request.headers.get('origin'); return !origin || origin === new URL(request.url).origin; }
export async function sourceKey(request: Request) { const config = await authConfig(); const source = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'local'; return hmac(source, config?.session_secret || 'light-ledger'); }
export async function changePassword(currentPassword: string, nextPassword: string) { if (!await verifyPassword(currentPassword)) return false; const bytes = new Uint8Array(16); crypto.getRandomValues(bytes); const salt = bytesToBase64(bytes); const iterations = 310_000; const hash = await passwordHash(nextPassword, salt, iterations); await getD1().prepare('UPDATE auth_config SET password_salt = ?, password_hash = ?, password_iterations = ?, session_version = session_version + 1, updated_at = ? WHERE id = 1').bind(salt, hash, iterations, new Date().toISOString()).run(); return true; }
