import { requireAuth } from '@/lib/auth'; import { ensureDatabase, getD1 } from '@/lib/database'; import { monthBounds } from '@/lib/http';
type Row = { id: string; type: 'expense' | 'income'; amountCents: number; title: string; occurredAt: string; categoryId: string | null; categoryName: string | null; categoryColor: string | null; categoryIcon: string | null; paymentMethod: string | null; attachmentCount: number };
function shiftMonth(month: string, delta: number) { const [year, number] = month.split('-').map(Number); const date = new Date(Date.UTC(year, number - 1 + delta, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`; }
export async function GET(request: Request) {
  const unauthorized = await requireAuth(request); if (unauthorized) return unauthorized; await ensureDatabase(); const current = monthBounds(new URL(request.url).searchParams.get('month')); const earliest = monthBounds(shiftMonth(current.month, -5)); const rows = await getD1().prepare(`SELECT t.id, t.type, t.amount_cents AS amountCents, t.title, t.occurred_at AS occurredAt, t.category_id AS categoryId, c.name AS categoryName, c.color AS categoryColor, c.icon AS categoryIcon, t.payment_method AS paymentMethod, (SELECT COUNT(*) FROM attachments a WHERE a.transaction_id = t.id AND a.deleted_at IS NULL) AS attachmentCount FROM transactions t LEFT JOIN categories c ON c.id = t.category_id WHERE t.deleted_at IS NULL AND t.occurred_at >= ? AND t.occurred_at < ? ORDER BY t.occurred_at DESC`).bind(earliest.start, current.end).all<Row>();
  const data = rows.results; const currentRows = data.filter((row) => row.occurredAt >= current.start && row.occurredAt < current.end); const previous = monthBounds(shiftMonth(current.month, -1)); const previousRows = data.filter((row) => row.occurredAt >= previous.start && row.occurredAt < previous.end);
  const total = (list: Row[], type: Row['type']) => list.filter((row) => row.type === type).reduce((sum, row) => sum + row.amountCents, 0);
  const expense = total(currentRows, 'expense'); const income = total(currentRows, 'income'); const previousExpense = total(previousRows, 'expense');
  const categoryMap = new Map<string, { id: string; name: string; color: string; icon: string; amountCents: number }>();
  currentRows.filter((row) => row.type === 'expense').forEach((row) => { const id = row.categoryId || 'uncategorized'; const value = categoryMap.get(id) || { id, name: row.categoryName || '未分类', color: row.categoryColor || '#77837e', icon: row.categoryIcon || 'Circle', amountCents: 0 }; value.amountCents += row.amountCents; categoryMap.set(id, value); });
  const trend = Array.from({ length: 6 }, (_, index) => { const month = shiftMonth(current.month, index - 5); const bounds = monthBounds(month); const group = data.filter((row) => row.occurredAt >= bounds.start && row.occurredAt < bounds.end); return { month, expense: total(group, 'expense'), income: total(group, 'income') }; });
  return Response.json({ month: current.month, summary: { expense, income, balance: income - expense, previousExpense, expenseChange: previousExpense ? (expense - previousExpense) / previousExpense : null }, categories: [...categoryMap.values()].sort((a, b) => b.amountCents - a.amountCents), trend, recent: currentRows.slice(0, 6) });
}
